### ISSUE TITLE
Incompatible with fisher block from MFR

### ISSUE THREAD

**Issue by Pilzinsel64** [jss2a98aj/BugTorch#28]
As soon as I install this mod in my modpack, the fisher block from MineFactory Reloaded starts to crash the world as soon as it want to work. See the stack trace. Even when disabling EVERY single option it still crashes.

I took a look at the source of MFR but had no look to saftly reproduce, not sure why. The code looks ok.

So, I might ask you here if you have an idea what could cause that.

```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.util.WeightedRandom.func_76273_a(WeightedRandom.java:30)
	at net.minecraft.util.WeightedRandom.func_76271_a(WeightedRandom.java:60)
	at net.minecraftforge.common.FishingHooks.getRandomFishable(FishingHooks.java:58)
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityFisher.activateMachine(TileEntityFisher.java:90)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:103)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1646)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Pilzinsel64** [comment]
After long time debugging I got it out probably: The option `cofhWorldTransformer` from hodgepodge did it in combination with BugTourch. Also I had to re-create the test-world every time to get a valid reason.

Sorry for bothering. Will test it on my prod instance tomorrow, but I am optimistic.
