### ISSUE TITLE
Incompatablity with Potion ID helper

### ISSUE THREAD

**Issue by SteamDoge9000** [jss2a98aj/BugTorch#5]
whenever the mentioned mod and this mod are present the game refuses to start up

The Error:

```Mixin prepare failed preparing minecraft.block.MixinBlockChest in mixins.bugtorch.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.bugtorch.json:minecraft.block.MixinBlockChest target net.minecraft.block.BlockChest was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.bugtorch.json:minecraft.block.MixinBlockChest target net.minecraft.block.BlockChest was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:522)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```

**Comment by jss2a98aj** [comment]
That crash doesn't have anything to do with potions.

**Comment by SteamDoge9000** [comment]
my bad melt me fix that
Its a mixin incompatability

**Comment by Roadhog360** [comment]
Have you tried turning off the B:brokenChestsDontSplitStacks option?

**Comment by SteamDoge9000** [comment]
ill look into it, ill get back to you asaIc

**Comment by makamys** [comment]
Looks like a Mixin - ASM incompatibility. Try using [Mixingasm](https://github.com/makamys/Mixingasm) and add the line
```
com.brandon3055.potionidhelper.asm.ClassTransformer
```
to your `.minecraft/config/mixingasm/transformer_exclusion_list.txt`.
